### ISSUE TITLE
Deployments broken on Chef 11. Recipe Compile Error ... compat_resource.

### ISSUE THREAD

**Issue by willdady** [aws/opsworks-cookbooks#383] opened 2016-05-26 04:12 UTC
Today we started getting build failures with the following error under Chef 11.10:

```
================================================================================
Recipe Compile Error in /var/lib/aws/opsworks/cache.stage2/cookbooks/compat_resource/libraries/autoload.rb
================================================================================


RuntimeError
------------
This resource is written with Chef 12.5 custom resources, and requires at least Chef 12.0 used with the compat_resource cookbook, it will not work with Chef 11.x clients, and those users must pin their cookbooks to older versions or upgrade.
```

According to [this thread](https://forums.aws.amazon.com/thread.jspa?messageID=720230) a opsworks built-in dependency, [build-essential](https://supermarket.chef.io/cookbooks/build-essential#changelog) recently added a breaking change. Can someone on the OpsWorks team please confirm this issue and provide a fix?

**Comment by jarv-aws** [comment] 2016-05-26 08:02
Assuming you have custom cookbooks that use build-essential the fix to this issue is to lock the version of build-essential to a compatible version (3.2.0 should work). The problem unfortunately cannot be fixed on the OpsWorks side because because it occurs when custom cookbooks are used that bring in compat_resource as a cookbook dependency.

**Comment by jweiss** [comment] 2016-05-26 09:45
Another solution is obviously to upgrade to Chef 12. This might be a little bit of effort as we do not feature the built-in layers but will give you the latest version of Chef and a lot more control over your cookbooks.

**Closed as completed by jweiss** 2016-05-26 09:45 UTC

**Comment by kjhangiani** [comment] 2016-06-02 23:11
Just wanted to point out for future googlers that we started experiencing this issue today (Jun 2, 2016).  It turned out to be due to an update that cookbook apt released today (4.0.0) that breaks backwards compatibility with chef 11.  We dep. locked apt to 3.0.0 in our Berksfile to fix this issue

`cookbook 'apt', '= 3.0.0'`

Here's the apt changelog: 

https://github.com/chef-cookbooks/apt/blob/master/CHANGELOG.md

**Comment by willdady** [comment] 2016-06-02 23:35
Our particular issue was caused by Ohai dropping support for Chef 11. We had to lockdown our Berksfile: 

`depends 'ohai', '= 3.0.1'`

**Comment by zeroedin** [comment] 2016-06-06 19:47
I think I'm having the same issue with the newrelic cookbook which depends on apt:

https://github.com/djoos-cookbooks/newrelic/blob/master/metadata.rb

I tried doing what @kjhangiani suggested and pining `cookbook 'apt', '= 3.0.0'` in my Berksfile, however I then get the following issue: 

```
cookbook 'apt', '= 3.0.0'
cookbook 'newrelic', '= 2.19.0'
cookbook 'timezone-ii', '= 0.2.0'
```

```
================================================================================
Error executing action `run` on resource 'ruby_block[Install the cookbooks specified in the Berksfile and their dependencies]'
================================================================================
 
 
Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '106'
---- Begin output of /opt/aws/opsworks/local/bin/berks vendor /opt/aws/opsworks/current/berkshelf-cookbooks ----
STDOUT: Resolving cookbook dependencies...
Fetching cookbook index from https://supermarket.chef.io...
STDERR: Unable to satisfy constraints on package apt due to solution constraint (newrelic = 2.19.0). Solution constraints that may result in a constraint on apt: [(apt = 3.0.0)], [(newrelic = 2.19.0) -> (apt ~> 2.0)]
Demand that cannot be met: (newrelic = 2.19.0)
Artifacts for which there are conflicting dependencies: apt = 4.0.0 -> [(compat_resource >= 0.0.0)]Unable to find a solution for demands: apt (= 3.0.0), newrelic (= 2.19.0), timezone-ii (= 0.2.0)
---- End output of /opt/aws/opsworks/local/bin/berks vendor /opt/aws/opsworks/current/berkshelf-cookbooks ----
Ran /opt/aws/opsworks/local/bin/berks vendor /opt/aws/opsworks/current/berkshelf-cookbooks returned 106
```

Anyone offer an solution to get around this problem?

**Comment by seanabrahams** [comment] 2016-07-03 20:07
This particular error is extremely frustrating because it does not report which dependency is causing the problem. In my case it was `librato/papertrail-cookbook` depending on `rsyslog`. Further, it took updating the `depends` line in `metadata.rb` (not just `Cheffile`) in a fork of `papertrail-cookbook` to a specific previous version to fix the issue. Look for what is depending on `compat_resource` to track down the problem dependency.

```
cd /var/lib/aws/opsworks/cache.stage2/cookbooks
grep -R 'compat_resource' .
```

For me it was revealed in `./rsyslog/metadata.json`

**Comment by mosheka** [comment] 2016-07-13 11:50
Happened to us as well w/ the combination of OpsWorks chef 11.10 and New Relic
@seanabrahams comment was very useful, and @jarv-aws  solved it for us:
`cookbook 'build-essential', '= 3.2.0'`

**Comment by stephenreid** [comment] 2016-08-16 14:37
@mosheka @kjhangiani Ran into this on Amazon OpsWorks yesterday. Added Ming to the list.

```
# Pin our version so that we still work in chef 11
 cookbook 'build-essential', '= 3.2.0'
 cookbook 'apt', '= 3.0.0'
 cookbook 'ming', '=1.2.3'
```

**Comment by kjhangiani** [comment] 2016-09-07 22:34
@mosheka @stephenreid

cookbook `windows` release of 2.0.0 and 2.0.1 both break chef 11 compatibility (9/7/2016 release)

https://github.com/chef-cookbooks/windows/blob/master/CHANGELOG.md

Using: `cookbook 'windows', '= 1.44.3'` to dep lock it now.  Another alternative if not using a windows machine is https://github.com/livinginthepast/windows-noop-cookbook but I did not try that and can't confirm if it works

**Comment by lesterchan** [comment] 2016-09-27 08:47
Just adding on, my cause was rsyslog, it was set to 4.0.1, fixing it to 2.2.0 solves the problem

**Comment by stephenreid** [comment] 2016-09-29 17:39
I am no longer finding Ming 1.2.3 in the supermarket. Anybody has a resource to use for the old version

**Comment by yonirotvel** [comment] 2016-11-22 13:21
Thanks alot @seanabrahams  ! Just to add ours, it was "yum-erlang_solutions" that had to be pinned to version 1.0.0

**Comment by zeroedin** [comment] 2016-11-22 18:00
I ran into this issue again today, is there a good way to identify what package changed and needs locked?  I already have the following locked via Berksfile: `'build-essential', '= 3.2.0'` and `'newrelic', '= 2.19.0'`.  Not sure how to figure out what package I need to lock next.  

Edit: Just saw @seanabrahams suggestion above, will try that.

**Comment by buremba** [comment] 2016-11-23 08:05
@zeroedin did you be able to solve the issue? i also run into same problem a few hours ago and not able to find the source package.

**Comment by yonirotvel** [comment] 2016-11-23 08:12
@zeroedin @buremba follow what @seanabrahams wrote, ssh into the machine and follow his commands, for me it was a custom cookbook that depended on a rabbit cookbook that depended on "yum-erlang_solutions". So start with greping the machine and post again if your stuck.
Best of luck, Thats one frustrating issue...

**Comment by buremba** [comment] 2016-11-23 10:47
Thanks @yonirotvel @seanabrahams, in my case the problem was `ohai` package, I didn't actually use that dependency but it seems that Opsworks depend on that package.

**Comment by yonirotvel** [comment] 2016-11-23 11:12
@buremba Me too, woke up today to find out that ohai broke me too :) followed @willdady to solve

**Comment by buremba** [comment] 2016-11-23 11:18
It's really shame that AWS does not offer a clean path upgrading 11.10 to 12. :( This is not the first issue that I run into because we're using 11.10, we want to upgrade to 12 but there are dozens of deployments of our customers and migrating all configurations to 12 is not trivial. We need to remove the stack, create new one with Chef 12 and move all the configurations.

**Comment by chadwick37** [comment] 2016-11-23 19:01
Yeah this is getting really old. Every other month I have to spend a day figuring out what is breaking and then pin the package to an older version.

**Comment by xgt001** [comment] 2016-11-28 12:13
For me the package that was causing it was yum-epel.

Adding this fixed it: 

`cookbook 'yum-epel', '= 0.7.1'`

**Comment by nelsonenzo** [comment] 2016-12-07 01:44
Today's fun-ness was ohai.
``` cookbook 'ohai', '= 3.0.1' ```

It took me a bit to figure out which cookbook was breaking as the error was not really clear.  For those coming across this, it's the cookbook in the logs right above compat_resource, which in my case was ohai.  Then go to the supermarket.io, look for your broken cookbook, and use the drop down to find the last release version that was Chef 11.
```
[2016-12-06T22:35:47+00:00] INFO: Storing updated cookbooks/ohai/resources/hint.rb in the cache.
[2016-12-06T22:35:47+00:00] INFO: Storing updated cookbooks/ohai/resources/plugin.rb in the cache.
[2016-12-06T22:35:47+00:00] INFO: Storing updated cookbooks/ohai/recipes/default.rb in the cache.
[2016-12-06T22:35:47+00:00] INFO: Storing updated cookbooks/ohai/libraries/matchers.rb in the cache.
[2016-12-06T22:35:47+00:00] INFO: Storing updated cookbooks/ohai/README.md in the cache.
[2016-12-06T22:35:47+00:00] INFO: Storing updated cookbooks/ohai/CONTRIBUTING.md in the cache.
[2016-12-06T22:35:48+00:00] INFO: Storing updated cookbooks/ohai/MAINTAINERS.md in the cache.
[2016-12-06T22:35:48+00:00] INFO: Storing updated cookbooks/ohai/CHANGELOG.md in the cache.
[2016-12-06T22:35:48+00:00] INFO: Storing updated cookbooks/ohai/metadata.json in the cache.
[2016-12-06T22:35:48+00:00] INFO: Storing updated cookbooks/compat_resource/libraries/autoload.rb in the cache.
[2016-12-06T22:35:48+00:00] INFO: Storing updated cookbooks/compat_resource/README.md in the cache.
[2016-12-06T22:35:48+00:00] INFO: Storing updated cookbooks/compat_resource/CONTRIBUTING.md in the cache.
[2016-12-06T22:35:48+00:00] INFO: Storing updated cookbooks/compat_resource/MAINTAINERS.md in the cache.
[2016-12-06T22:35:48+00:00] INFO: Storing updated cookbooks/compat_resource/CHANGELOG.md in the cache.
[2016-12-06T22:35:48+00:00] INFO: Storing updated cookbooks/compat_resource/metadata.json in the cache.
```

**Comment by jamesallsup** [comment] 2016-12-12 04:00
@seanabrahams I have lost my mind so many times trying to find issues in the logs, your bit of advice helped me find an issue in ~10s....thank you!! Can't believe it never crossed my mind to grep the cache

`cd /var/lib/aws/opsworks/cache.stage2/cookbooks
grep -R 'compat_resource' .`

**Comment by ardeearam** [comment] 2016-12-12 06:41
@nelsonenzo @willdady The ohai fix worked. And for that I am eternally grateful (bow)

**Comment by echery** [comment] 2016-12-21 20:39
If you have another OpsWorks stack with the same recipes loaded, you can try to remove one recipe at a time and keep testing the deployment until everything passes. This helped me find the culprit.

In my case, the DataDog agent recipe was causing issues for me and there was documentation available to get it running with Chef 11.

**Comment by chadwick37** [comment] 2017-01-04 22:28
Back again for more broken deployments. Come on AWS, you are better than this. Update Chef already!

**Comment by jweiss** [comment] 2017-01-04 23:45
The issue is that you are using a newer version of a cookbook that requires a newer Chef version. We recommend pinning the version of your cookbook dependencies so that updates like this don't surprisingly break you.

We are offering a newer Chef version for over a year now: https://aws.amazon.com/blogs/devops/aws-opsworks-now-supports-chef-12-for-linux/

We recommend to upgrade to Chef 12 as it offers much better support for community cookbooks.

**Comment by elvizcacho** [comment] 2017-01-05 16:37
I'm getting this error running the setup command on Opworks in AWS:

```
================================================================================
Recipe Compile Error in /var/lib/aws/opsworks/cache.stage2/cookbooks/homebrew/libraries/homebrew_mixin.rb
================================================================================
 
 
NameError
---------
uninitialized constant Chef::Mixin::HomebrewUser
 
 
Cookbook Trace:
---------------
/var/lib/aws/opsworks/cache.stage2/cookbooks/homebrew/libraries/homebrew_mixin.rb:23:in `<class:Chef12HomebrewUser>'
/var/lib/aws/opsworks/cache.stage2/cookbooks/homebrew/libraries/homebrew_mixin.rb:22:in `<top (required)>'
```

These are my current cookbooks

cookbook 'build-essential', '= 3.2.0'
cookbook 'apt', '= 3.0.0'
cookbook 'nodejs', '~> 2.4.4'
cookbook 'ohai', '= 3.0.1'
cookbook 'yum-epel', '= 0.7.1'

Does somebody has any idea what dependency could be causing the error?

**Comment by elvizcacho** [comment] 2017-01-05 17:13
[Solved]

Homebrew cookbook doesn't support chef11 anymore . I had to freeze Homebrew version to 2x

This is how the Berksfile looks like now:

```
source 'https://supermarket.chef.io/'

  cookbook 'build-essential', '= 3.2.0'
  cookbook 'apt', '= 3.0.0'
  cookbook 'nodejs', '~> 2.4.4'
  cookbook 'ohai', '= 3.0.1'
  cookbook 'yum-epel', '= 0.7.1'
  cookbook 'homebrew', '= 2.1.2'

```

Cheers!

**Comment by xgt001** [comment] 2017-01-06 09:11
@elvizcacho also - the Homebrew dependency is unnecessary unless you actually want MacOS support from nodejs cookbook. This will also save a few seconds from your deploy :)

**Comment by Bellardia** [comment] 2017-01-20 06:12
yum-repoforge must also be locked, which is a sub-dependency of consul. What a mess.

`cookbook 'yum-repoforge', '~> 1.0.0'`

**Comment by mstubna** [comment] 2017-03-01 15:13
recent versions of yum can also cause [an issue](https://forums.aws.amazon.com/thread.jspa?messageID=767127&tstart=0). Locking it to 4.2.0 works for me:

`cookbook 'yum', '= 4.2.0'`
