### ISSUE TITLE
Chef unable to find my app directory from /srv/www/

### ISSUE THREAD

**Issue by chetandhembre** [aws/opsworks-cookbooks#213] opened 2014-09-13 06:27 UTC
Hi, 
   From last one week my opswork instances are failing abruptly without some weird resome following is log of it

```
[2014-09-11T19:07:15+00:00] ERROR: Running exception handlers
[2014-09-11T19:07:15+00:00] ERROR: Exception handlers complete
[2014-09-11T19:07:15+00:00] FATAL: Stacktrace dumped to /var/lib/aws/opsworks/cache.stage2/chef-stacktrace.out
[2014-09-11T19:07:15+00:00] ERROR: directory[/srv/www/image_maker/shared] (deploy::nodejs line 3) had an error: Errno::ENOENT: No such file or directory - /srv/www/image_maker
[2014-09-11T19:07:15+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

and below is compiled version of chef resource which causing this error

```
# Declared in /var/lib/aws/opsworks/cache.stage2/cookbooks/deploy/definitions/opsworks_deploy_dir.rb:3:in `block in from_file'

directory("/srv/www/image_maker/shared") do
params {:user=>"deploy", :group=>"www-data", :path=>"/srv/www/image_maker", :name=>nil}
provider Chef::Provider::Directory
action [:create]
retries 0
retry_delay 2
path "/srv/www/image_maker/shared"
recursive true
cookbook_name "deploy"
recipe_name "nodejs"
mode 504
owner "deploy"
group "www-data"
end
```

I really do not know whats going on here ? Can someone help me ?
When I spin new instance for same configuration all works fine. But after some time (in days) instance failed with above error. If i tried to restart it, It gives some error.

**Comment by aliw77** [comment] 2014-10-08 04:04
I am also having same issue - had an issue open on AWS formus for more than 3 weeks now and no resolution.  Restarting EBS backed instance always results in this error (even with custom AMI).  I can only use instance store and live with the resulting 20 minutes times to have load based instance kick in. In my case i see the log complain about unicorn versions.  Gemfile has no unicorn.

line 365 onwards:

```
[2014-10-08T04:02:56+00:00] INFO: Processing ruby_block[ensure only our unicorn version is installed by deinstalling any other version] action run (unicorn::default line 1)
[2014-10-08T04:02:57+00:00] INFO: Skipping installation of version 4.7.0 of Rubygem unicorn: already installed
[2014-10-08T04:02:57+00:00] INFO: ruby_block[ensure only our unicorn version is installed by deinstalling any other version] called
[2014-10-08T04:02:57+00:00] INFO: Processing group[www-data] action create (unicorn::rails line 4)
[2014-10-08T04:02:57+00:00] INFO: Processing user[deploy] action create (unicorn::rails line 6)
[2014-10-08T04:02:57+00:00] INFO: Processing directory[/srv/www/mywebapp/shared] action create (unicorn::rails line 3)

================================================================================
Error executing action `create` on resource 'directory[/srv/www/mywebapp/shared]'
================================================================================


Errno::ENOENT
-------------
No such file or directory - /srv/www/mywebapp


Resource Declaration:
---------------------
# In /var/lib/aws/opsworks/cache.stage2/cookbooks/deploy/definitions/opsworks_deploy_dir.rb

3:   directory "#{params[:path]}/shared" do
4:     group params[:group]
5:     owner params[:user]
6:     mode 0770
7:     action :create
8:     recursive true
9:   end
```

**Comment by chetandhembre** [comment] 2014-10-10 05:21
Any one have solved this issue ?

**Comment by anatolymd** [comment] 2014-11-12 15:38
Same problem here. When an instance is created from scratch, there are no problems at all. If I run stack's "setup" command or if I stop and then start an instance, it fails. 
Here's the log:

```
[2014-11-12T15:29:38+00:00] INFO: Processing directory[/srv/www/webapp/shared] action create (deploy::php line 3)

================================================================================
Error executing action `create` on resource 'directory[/srv/www/webapp/shared]'
================================================================================


Errno::ENOENT
-------------
No such file or directory - /srv/www/webapp


Resource Declaration:
---------------------
# In /var/lib/aws/opsworks/cache.stage2/cookbooks/deploy/definitions/opsworks_deploy_dir.rb

3:   directory "#{params[:path]}/shared" do
4:     group params[:group]
5:     owner params[:user]
6:     mode 0770
7:     action :create
8:     recursive true
9:   end
10: 



Compiled Resource:
------------------
# Declared in /var/lib/aws/opsworks/cache.stage2/cookbooks/deploy/definitions/opsworks_deploy_dir.rb:3:in `block in from_file'

directory("/srv/www/webapp/shared") do
params {:user=>"deploy", :group=>"www-data", :path=>"/srv/www/webapp", :name=>nil}
provider Chef::Provider::Directory
action [:create]
retries 0
retry_delay 2
path "/srv/www/webapp/shared"
recursive true
cookbook_name "deploy"
recipe_name "php"
mode 504
owner "deploy"
group "www-data"
end
```

**Comment by anatolymd** [comment] 2014-11-12 16:02
syslog is showing a lot of errors while trying to mount EBS storage (my instances use EBS)

```
Nov 12 15:29:42 php-app2 automount[841]: failed to mount /srv/www
Nov 12 15:29:42 php-app2 automount[841]: attempting to mount entry /srv/www
Nov 12 15:29:42 php-app2 automount[841]: failed to mount /srv/www
Nov 12 15:29:42 php-app2 automount[841]: attempting to mount entry /srv/www
Nov 12 15:29:42 php-app2 automount[841]: failed to mount /srv/www
Nov 12 15:29:47 php-app2 automount[841]: attempting to mount entry /srv/www
Nov 12 15:29:47 php-app2 automount[841]: failed to mount /srv/www
Nov 12 15:29:47 php-app2 automount[841]: attempting to mount entry /srv/www
Nov 12 15:29:47 php-app2 automount[841]: failed to mount /srv/www
Nov 12 15:29:57 php-app2 automount[841]: attempting to mount entry /srv/www
Nov 12 15:29:57 php-app2 automount[841]: failed to mount /srv/www
Nov 12 15:29:57 php-app2 automount[841]: attempting to mount entry /srv/www
Nov 12 15:29:57 php-app2 automount[841]: failed to mount /srv/www
Nov 12 15:30:07 php-app2 automount[841]: attempting to mount entry /srv/www
Nov 12 15:30:07 php-app2 automount[841]: failed to mount /srv/www
Nov 12 15:30:07 php-app2 automount[841]: attempting to mount entry /srv/www
Nov 12 15:30:07 php-app2 automount[841]: failed to mount /srv/www
Nov 12 15:30:17 php-app2 automount[841]: attempting to mount entry /srv/www
Nov 12 15:30:17 php-app2 automount[841]: mounted /srv/www
```

EBS was mounted way later then Chef was trying to access that folder in the log from above.

**Comment by pschrammel** [comment] 2014-12-22 12:29
Hi, this is a real showstopper for me. Any workarounds already?
THX

**Comment by tbuser** [comment] 2014-12-29 20:58
I had the same problem when using Ubuntu, but the problem seems to have went away when I switched to Amazon Linux 2014.09.

**Comment by xjlu** [comment] 2014-12-30 06:14
Having the same issue here. Standard rails app layer, ubuntu 14.04 or 12.04, both failed the setup step consistently when starting an instance from the stopped state. Also, thanks to this issue, the autoscale option is totally broken currently. 

I searched this issue on aws forum, and seems like it's been an issue for a while, but was never fixed or somehow no one got to the bottom of it. _NOTE_ as @jarv mentioned, I have created a ticket to technical support and they are still working on a fix.

The workaround that works in my case is to override the `deploy_to` attribute in custom JSON. The default value is `/srv/www/`, which is supposedly a mount point for `/mnt/srv/www`. Instead, I am overriding it 

``` js
{
    "deploy" : { 
        "name_of_your_app" : { 
            "deploy_to" : "/mnt/srv/www/name_of_your_app" 
            }
        }
}
```

I am still seeing the mount failure, but it won't fail the setup anymore since the ephemeral storage eventually got mounted after a few tries. **NOTE**: after this change, stop and start all instances so that it can pick up the new path, otherwise it won't be able to soft reboot unicorn processes or whatever processes you are running.

Another possible solution is to use EBS volume, mount it at `/mnt/www`, then symlink `/srv/www` to it. This is detailed in the opsworks documentation, too.

**Comment by panagioto** [comment] 2015-01-14 19:07
Same issue here...i have not managed to find a workaround yet.

```
2015-01-14T18:55:12+00:00] INFO: Processing directory[/srv/www/testing_app/shared] action create (deploy::nodejs line 3)

================================================================================
Error executing action `create` on resource 'directory[/srv/www/testing_app/shared]'
================================================================================


Errno::ENOENT
-------------
No such file or directory - /srv/www/testing_app
```

Any help?

**Comment by xjlu** [comment] 2015-01-14 19:33
Have you tried my workaroud? That is, change the deploy to path.

**Comment by panagioto** [comment] 2015-01-14 20:29
xjlu thanks... i had tried your workaround but i had made a mistake...Now works, thanks again.

**Comment by pschrammel** [comment] 2015-01-15 09:19
Where do you set the deploy_to attribute? In the stack's custom json property?

**Comment by panagioto** [comment] 2015-01-15 09:35
Yes, in the stack's custom json like that:

```
{
"deploy" : { 
      "name_of_your_app" : { 
               "deploy_to" : "/mnt/srv/www/name_of_your_app" 
                                           }
                }
}
```

**Comment by ejsantos** [comment] 2015-02-04 07:20
This seems to be happening when using EC2 types with **Instance store** available for **Root device type**. At lease this is what I observe in our case.

My scenario:

Scenario 1:
Did **NOT** use the workaround as stated above using custom JSON. Used an AMI with EBS attached that was created from a t2.micro instance. Boot an instance with t2.medium (Instance store is unavailable option if you didn't select Custom AMI in Operating System) -> this worked

Scenario 2:
Same setting as above _but_ use m3.large -> this failed

I'm still not sure if the instance used to create an AMI plays a role here since t2.micro does not have Instance store available as well. I wonder if I create an AMI from an m3.large, will scenario 1 fail and scenario 2 work? Do you guys have the same experience?

**Comment by btsai** [comment] 2015-02-05 09:13
Thank you xjlu - your recommendation to add the deploy node to the custom json worked:

```
{
"deploy" : { 
      "name_of_your_app" : { 
               "deploy_to" : "/mnt/srv/www/name_of_your_app" 
                                           }
                }
}
```

This has been happening ever since I switched to c3.large. Totally made using time-based instances impossible.

**Comment by agrass** [comment] 2015-03-16 18:32
Today I started to have this same issue on setup stage (I have been deploying for like two weeks without this problem).  It's weird because when I run setup again manually it works. It's there a way to solve it not changing the deploy_to path??

**Comment by kyleblarson** [comment] 2015-03-19 18:41
I started encountering this on a r3.large instance once I mounted instance storage to /db_backups for storage of temporary files during backups.  Strange indeed.  I have 10 running instances and have done hundreds of deployments with no issue, and only started seeing the error on the one instance.

**Comment by electronym** [comment] 2015-03-25 18:41
+1 here

Having the same issue with EBS-backed instances and only when starting a pre-existing instance from a stopped state. New instances are fine, and manually running "setup" on the failed instance fixes it, but it's not a viable solution.

I'm going to attempt xjlu's workaround, but I'm concerned about creating downstream issues if I change the deploy_to directory, since I have a ton of custom recipes built on top of this. And it's pretty clunky to have to do this in the first place.

**Comment by agrass** [comment] 2015-03-25 21:07
I have given up with another solution for this issue, I was in the same condition of you @electronym, with a lot of custom recipes but finally I used the workaround of xjlu

**Comment by xjlu** [comment] 2015-03-25 23:45
@agrass Well, intuitively, the setup failed at opsworks_deploy_dir.rb, because the folder `/srv/www/app_name` was not available YET at that moment. A bandage fix would be to wait for it at that step. My bet is that there is an ordering issue with the built-in recipes, though. Since the issue can be reproduced fairly easily,  I wish it had a bug tracking system.

**Comment by btsai** [comment] 2015-03-25 23:59
This seems to be a consistent and reproducible error, so I would assume that this affects pretty much anyone using the larger instances. Yet 6 months later, it still hasn't been fixed.

Does anyone have AWS with technical support, so that they can be notified and finally get this some attention?

**Comment by jarv** [comment] 2015-03-31 12:17
Opsworks is aware of this issue and is actively working on a fix so that the custom json workaround won't be necessary. I will keep have an update in the next week or two, in the meantime please use the workaround above.

**Comment by jarv** [comment] 2015-05-11 16:10
Apologize for the delay in updating this issue. Unfortunately the fix for this was not as straightforward as we thought due to a mounting race condition. We are still trying to address the issue but for now the workaround in the custom json above will be necessary.

**Comment by inket** [comment] 2015-05-13 04:24
I have tried the workaround but it seems that it prevents instance store instances from deploying to the correct directory. So after a deploy, nothing changes on the user's side.

Thoughts?

**Comment by xjlu** [comment] 2015-05-13 05:24
@inket if it's an existing instance, you need to stop and restart to pick up the new setting. I have boldfaced my original comment to emphasize it.

**Comment by inket** [comment] 2015-05-13 05:43
@xjlu Oh, sorry. I read the thread a few months ago and didn't need the workaround until today. Thank you!

**Comment by jarv** [comment] 2015-07-24 13:01
Hello - for those who are monitoring this issue I want to let you know that we haven't forgotten about it. If anyone has a reliable way with a configuration they can share to reproduce the failure it would be useful as I have been unable to reproduce the issue myself by stopping and starting an instance (both ebs and instance store, various instance types). We want to be extremely careful that changes made here do not break any existing users who are overriding attributes. One possible fix may be to simply add retries on the directory creation which may address some of the failures that were reported in the thread.

**Comment by diegodurante** [comment] 2016-03-09 13:54
Hi everybody,
maybe I found the problem.

The problem is related to the update of OpsWorks agent version.

I was using the 3428 version with no problems.
Today in the amazon panel I founded this warning:
"Please update the OpsWorks agent version to the latest (3433).
This new version addresses a problem with downloading a dependency during instance setup. Newly launched instances will fail their setup unless you upgrade. You can select the agent version in the stack settings."

But after updating the stack to the 3433 version I started to have the problem because seems that with this version my app git repository is not downloaded and so the folder /srv/www/ is not created at all.

What do you think?

**Closed as completed** 2018-11-05 12:58 UTC
