### ISSUE TITLE
Failure to load custom cookbooks that are Git repositories

### ISSUE THREAD

**Issue by fancyremarker** [aws/opsworks-cookbooks#97] opened 2014-01-14 01:11 UTC
If I specify an HTTP archive for my custom cookbooks, and that compressed archive contains a folder which is a Git repository, it will not be properly copied to /opt/aws/opsworks/current/site-cookbooks.

The reason is that by [initializing](https://github.com/aws/opsworks-cookbooks/blob/master-chef-11.4/scm_helper/libraries/archive.rb#L31) a new repository in the top-level custom cookbooks directory, and then [cloning](https://github.com/aws/opsworks-cookbooks/blob/master-chef-11.4/opsworks_custom_cookbooks/recipes/checkout.rb#L35) that newly-initialized repository, any Git repository subdirectories will be ignored.

Simply copying the archive to the destination would obviate this problem. Is that not possible?

**Comment by githuesch** [comment] 2014-01-14 10:32
When you use the HTTP/S3 sources for cookbooks or apps, your archive is downloaded and extracted. Afterwards, a git repository is initialized. For that to succeed, a top-level .git directory is deleted, if present at all.

https://github.com/aws/opsworks-cookbooks/blob/master-chef-11.4/scm_helper/libraries/archive.rb#L31
https://github.com/aws/opsworks-cookbooks/blob/master-chef-11.4/scm_helper/libraries/s3.rb#L29

It seems this deletion should be done recursively to account for git repositories in subdirectories.

In the meantime, when you can just omit those git directories, that would be an easy workaround.

**Comment by fancyremarker** [comment] 2014-01-14 13:19
@githuesch: Thanks for the response. Omitting the git directories is a good suggestion for a workaround, and exactly what I'll be doing at the moment.

One of the reasons that this is such a pain point is that by default, when using Berkshelf to manage dependencies, running `berks package` creates an archive which very conveniently matches the format (several top-level cookbook folders) expected by OpsWorks. Unfortunately, the root cookbook from which `berks package` is run, along with any cookbooks fetched from Git remotes (rather than the Opscode repository), will be Git repositories within this tarball. So, before uploading, one must remember to uncompress the tarball, remove all `.git` folders recursively, and then re-compress.

With Berkshelf growing as the community standard, fixing this would make OpsWorks deployment easier for many.

**Comment by githuesch** [comment] 2014-01-14 14:29
How do you actually get this to break? I just deployed an app that contains a git repo in a subdirectory, and all the contents survive. I know I could just recursively delete all .git directories, but I'd like to see it break before I fix it.

**Comment by mfrister** [comment] 2014-01-14 15:19
I'm not sure this is the same problem, but adding bare Git repositories to another repository doesn't work well.
For bare repositories, Git creates a `refs` directory and a `tags` and a `heads` directory within that. These directories may be empty, so they're not possible to add to a Git repository. When accessing the bare repository after a clone of the outer repository, Git nevertheless expects the `refs` directory to exist and uses it as an indicator to determine whether a directory contains a Git repository.

An ugly workaround is adding empty `.gitkeep` files to the `refs` directories. I think nesting Git repositories is not expected by Git and doesn't seem to be a good idea.

We have this problem with bundled Ruby Gems that contain bare repositories and have to use the ugly workaround described above.

Not committing HTTP/S3 archives to a Git repository also seems a good idea regarding deployment duration.

Are there any chances you could change the deployment process for HTTP/S3 archives to not commit everything to a Git repository?

**Comment by fancyremarker** [comment] 2014-01-14 16:12
@githuesch I put up an example app, with instructions for reproducing the bug, here:
https://github.com/fancyremarker/opsworks-breaking-examples

What causes the breakage is the few simple steps in fancyremarker/opsworks-breaking-examples@9c1755e037ac43f0c3e1b03d3573fdfd6bb899db

**Comment by githuesch** [comment] 2014-01-14 18:24
@meeee Also not sure if that's the same, but it would be great if you could also provide an example archive that exposes the issue you describe.

@fancyremarker Great, I'll try this out, and see if my change does the trick.

**Comment by mfrister** [comment] 2014-01-15 09:27
@githuesch Here's a test archive: https://s3-eu-west-1.amazonaws.com/deploy-experiments/opsworks-test-archive.tar.gz

I created a sample Ruby Sinatra application, using Bundler and fetching sinatra via Git. I installed the dependencies via `bundle install --path=vendor/bundle`.

Here's how you can reproduce the problem:

```
$ curl https://deploy-experiments.s3-eu-west-1.amazonaws.com/opsworks-test-archive.tar.gz > opsworks-test-archive.tar.gz
$ tar xf opsworks-test-archive.tar.gz
$ cd opsworks-test-archive
$ # here it'll work
$ bundle exec ruby hi.rb
[2014-01-15 09:54:41] INFO  WEBrick 1.3.1
[2014-01-15 09:54:41] INFO  ruby 2.0.0 (2013-06-27) [x86_64-darwin12.3.0]
== Sinatra/1.4.4 has taken the stage on 4567 for development with backup from WEBrick
[2014-01-15 09:54:41] INFO  WEBrick::HTTPServer#start: pid=28108 port=4567

$ # the bare repo exists
$ find vendor/bundle/ruby/2.0.0/cache/bundler/git/sinatra-cc08bfcbc5c59270b51521e6851c38b1f26da241/refs
vendor/bundle/ruby/2.0.0/cache/bundler/git/sinatra-cc08bfcbc5c59270b51521e6851c38b1f26da241/refs
vendor/bundle/ruby/2.0.0/cache/bundler/git/sinatra-cc08bfcbc5c59270b51521e6851c38b1f26da241/refs/heads
vendor/bundle/ruby/2.0.0/cache/bundler/git/sinatra-cc08bfcbc5c59270b51521e6851c38b1f26da241/refs/tags

$ # Command from Opsworks cookbooks for creating the Git Repository
$ # See https://github.com/aws/opsworks-cookbooks/blob/master-chef-11.4/scm_helper/libraries/s3.rb#L29
$ rm -rf .git; git init; git add .; git commit -m 'Create temporary repository from downloaded contents.'
Initialized empty Git repository in .../Projects/opsworks-test-repository/.git/
[master (root-commit) 8fb4402] Create temporary repository from downloaded contents.
 Author: ...
 312 files changed, 28116 insertions(+)
 create mode 100644 .bundle/config
 create mode 100644 .bundle/install.log
 create mode 100644 Gemfile
 create mode 100644 Gemfile.lock
 create mode 100644 README.md
 create mode 100644 hi.rb
 ...

$ cd ..
$ git clone opsworks-test-archive opsworks-test-clone
Cloning into 'opsworks-test-clone'...
done.
$ cd opsworks-test-clone

$ # doesn't work any more
$ bundle exec ruby hi.rb
Could not find sinatra-1.4.4 in any of the sources
Run `bundle install` to install missing gems.

$ # the bare repo is missing the refs directory
$ find vendor/bundle/ruby/2.0.0/cache/bundler/git/sinatra-cc08bfcbc5c59270b51521e6826da241/refs
find: vendor/bundle/ruby/2.0.0/cache/bundler/git/sinatra-cc08bfcbc5c59270b51521e6851c38b1f26da241/refs: No such file or directory
```

**Comment by githuesch** [comment] 2014-01-15 11:09
@fancyremarker Removing the .git directories recursively fixes your case, I was able to run docker::default with this change in place. Needs more thorough testing.

@meeee Thanks for your example, I'll look into it.

**Comment by fancyremarker** [comment] 2014-01-15 14:33
Thanks for taking the time to look into this, @githuesch.

Am I correct in assuming that there's no way to patch the `opsworks-custom-cookbooks` recipes with my own custom cookbook? Seems like there's a chicken-and-egg problem there.

Also, it seems as though the `master-chef-11.4` branch of this repo is kept consistent with what's deployed in production — is that correct?

**Comment by githuesch** [comment] 2014-01-15 15:44
@fancyremarker You can override attributes, templates, and definitions. You can't override recipes. That's true in general, not just for this cookbook. When you feel the need to override one of our recipes, that probably means that something needs to be made more adaptable on our end.

The code in this repo is kept consistent with what's in production, but with some delay. That's because our authoritative repositories are internal, and we push to Github for customer visibility.

**Comment by githuesch** [comment] 2014-01-23 11:47
@meeee I looked into your archive but didn't find an easy way to fix this yet. We're rolling out a fix for @fancyremarker's issue. I agree it's somewhat similar, but _not_ the same.

If you have control over how your archive is assembled, my recommendation would be to only have the contents you want to deploy in there, not a bare repo.

**Comment by mfrister** [comment] 2014-01-23 12:45
@githuesch Thanks for looking into the archive! Unfortunately the bare repository is nothing we create ourselves, but something Bundler creates when running `bundle install --path` and complains about when you delete it.

We have an ugly workaround (creating empty files in the bare repository folder, so git has files to store), but I also think creating a Git repository from a tarball is a bad idea. If not for problems with Git itself, it also takes quite some time during deployment (our application including dependencies is > 200 MB) and also nearly doubles (depending on how well git compresses) disk usage. This is especially a concern when using the recently released m3.medium instance with only 4 GB of SSD storage.

I'd love Opsworks to deploy tarballs without creating a temporary Git archive from them.

**Comment by githuesch** [comment] 2014-01-23 13:11
@meeee I agree wholeheartedly, for all the reasons you mentioned. The reason we're creating the temporary repo is that it lets us use Chef's built-in deploy resource for all our supported sources. There's currently no way I know of to deploy with Chef from a local directory, and searching through forums indicates that we're not the only ones waiting for this. There's a community cookbook that handles fetching and extraction of archives in a generic way (http://community.opscode.com/cookbooks/archive), but integrating this with our deployment is not a trivial change either.

Anyways, thanks a lot for your input. We will improve the experience with archives, but I can't give you an ETA.

**Comment by mfrister** [comment] 2014-01-23 13:41
@githuesch I see. Thanks for sharing more detail on this and I'm looking forward to your improvements.

**Comment by githuesch** [comment] 2014-01-27 07:12
@fancyremarker Your issue should be fixed now. Can you confirm?

**Comment by fancyremarker** [comment] 2014-01-28 15:31
Hey @githuesch, I just tested with the same example repo as before ([fancyremarker/opsworks-breaking-examples](/fancyremarker/opsworks-breaking-examples)), and got the same error as before:

```
[2014-01-28T15:24:26+00:00] INFO: New Run List expands to ["opsworks_initial_setup", "ssh_host_keys", "ssh_users", "mysql::client", "dependencies", "ebs", "opsworks_ganglia::client", "opsworks_stack_state_sync", "opsworks-breaking-examples::issue97", "deploy::default", "test_suite", "opsworks_cleanup"]
[2014-01-28T15:24:26+00:00] ERROR: Caught exception while compiling OpsWorks custom run list: Chef::Exceptions::CookbookNotFound - Cookbook opsworks-breaking-examples not found. If you're loading opsworks-breaking-examples from another cookbook, make sure you configure the dependency in your metadata - /opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/cookbook/cookbook_collection.rb:38:in `initialize'
/opt/aws/opsworks/releases/20131222191101_216/vendor/bundle/ruby/1.8/gems/ohai-6.16.0/lib/ohai/mash.rb:77:in `call'
/opt/aws/opsworks/releases/20131222191101_216/vendor/bundle/ruby/1.8/gems/ohai-6.16.0/lib/ohai/mash.rb:77:in `default'
/opt/aws/opsworks/releases/20131222191101_216/vendor/bundle/ruby/1.8/gems/ohai-6.16.0/lib/ohai/mash.rb:77:in `default'
/opt/aws/opsworks/releases/20131222191101_216/vendor/gems/chef-11.4.4/bin/../lib/chef/run_context/cookbook_compiler.rb:265:in `[]'
```

**Comment by fancyremarker** [comment] 2014-01-28 15:52
Also, to confirm: if I manually remove all `.git` subfolders (`rm -rf */.git`) from the cookbooks directory before uploading the tarball, the deploy runs successfully.

**Comment by githuesch** [comment] 2014-01-28 15:52
D'oh, my mistake. Looking at your log snippet I can see that you're not running the latest version of our agent yet. You don't have to do anything, just wait. I'll bump this issue again once the new agent rollout is _really_ complete.

**Comment by fancyremarker** [comment] 2014-01-28 15:56
No worries! No rush on my end, but thanks again for implementing the fix for this. I'll test it again once it's released.

**Comment by githuesch** [comment] 2014-02-10 16:01
@fancyremarker next attempt, should work now

**Comment by fancyremarker** [comment] 2014-02-10 16:50
Worked like a charm! Thanks @githuesch.

**Comment by githuesch** [comment] 2014-02-10 17:04
@fancyremarker Glad to hear that.
@meeee I can keep this one open and update it once we have an improvement for your case, or I can close it and you open another issue for bare repos. Whichever you prefer.

**Comment by mfrister** [comment] 2014-02-10 17:10
@githuesch Keeping this open means less work for me, so let's do that :)

**Comment by jweiss** [comment] 2018-11-05 12:55
closing as this is a very old issue

**Closed as completed by jweiss** 2018-11-05 12:55 UTC
