### ISSUE TITLE
RDS Support does not work with Rails Application and non-MySQL database

### ISSUE THREAD

**Issue by mfrister** [aws/opsworks-cookbooks#136] opened 2014-05-15 08:23 UTC
I tried to use a Postgres RDS database.

The cookbooks don't correctly set the database type in `config/database.yml`.

Apparently `deploy["database"]["adapter"]` is not set, but only `deploy["database"]["type"]`, [which is not used by the rails cookbook](https://github.com/aws/opsworks-cookbooks/blob/release-chef-11.4/rails/templates/default/database.yml.erb#L3). The cookbooks seem to require `adapter` to be set and default to `mysql2` when it's not:

```
INFO: No database adapter specified for <APP NAME>, guessing
INFO: Looks like <APP NAME> is a Rails 3 application, defaulting to mysql2
```

This results in the database connection failing.

As a workaround, I set deploy["database"]["adapter"] for the application in the Stack JSON.

**Comment by jweiss** [comment] 2014-05-15 08:35
We also addressed this internally and a fix will be rolled out very soon.

As you mentioned, the workaround is to either 1) override the deploy["database"]["adapter"] value via custom JSON or in an attribute file or 2) to override the database.yml template.

We will update this issue as soon as the fix is deployed.

**Comment by sudhirj** [comment] 2014-05-22 08:46
Sigh. This broke our production app (Rails + Postgres on RDS) without warning. I wound up writing a bunch of deployment shell scripts and moving off Opsworks to Autoscalinggroups + cloud init.

**Comment by jweiss** [comment] 2014-05-22 09:18
@sudhirj I'm interested in how this broke you. We only send an additional parameter 'type' that wasn't there before.

**Comment by sudhirj** [comment] 2014-05-22 10:07
A day before the announcement was made, our deploys (with migrations) began to fail. On looking at the logs, we realized that the `rake db:migrate` step was failing. This was odd because the app was working fine on production with no issues. 

I tried turning the migrations off and deploying. Big mistake. Now the deploy went through fine (And opsworks gave me all green checks) but the app couldn't connect to the database. To top it all off, adding an SSH key to an instance didn't seem to work either. 

After much stopping and starting and experimenting with different instances and types and double checking settings (no changes, deploys always succeeded but results in an app that couldn't connect), I gave up and moved off OpsWorks.

That was about 8 hours or downtime, and me sitting up till 3AM trying to get prod back up. Decided I'd rather stick to shell scripts.

**Comment by sudhirj** [comment] 2014-05-22 10:13
I'm not sure if it was the type parameter or the new IAM role requirement, but something broke connectivity between the app server layer and RDS/Postgres with no warning. No security groups were changed.

**Comment by awsrequena** [comment] 2014-08-20 13:31
Same problem as pull request https://github.com/aws/opsworks-cookbooks/pull/166

**Comment by baruchlubinsky** [comment] 2014-10-03 11:28
To be explicit with the workaround. I've had to add this JSON to my deployment:

```
{"deploy":{"api":{"database":{"adapter":"postgresql","type":"postrgesql"}}}}  
```

where `api` is the name of my application in OpsWorks.

**Comment by Xantax** [comment] 2014-10-03 15:37
or something like this:

```
{
  "deploy": {
    "myappname": {
      "database": {
        "adapter": "postgresql",
        "encoding": "unicode",
        "host": "myappname.nil.us-east-1.rds.amazonaws.com",
        "port": "5432",
        "database": "mydatabase",
        "pool": "5",
        "username": "secretusername",
        "password": "secretpass"
      }
    }
  }
}
```

**Comment by mshappe** [comment] 2014-12-17 00:23
So, I've added a clause like the above to my deployment...and it still seems to be falling back to MySQL. Any other ideas? :-)

**Comment by james075** [comment] 2014-12-26 20:22
> So, I've added a clause like the above to my deployment...and it still seems to be falling back to MySQL. Any other ideas? :-)

up ?

**Comment by mshappe** [comment] 2014-12-26 20:25
It never did work. I gave up. OpsWorks was an experiment for me. It failed for now. I'll try again when Amazon stops dragging its heels and supports PostgreSQL properly.

**Comment by zacstewart** [comment] 2015-01-27 16:06
Seems like this is still an issue. The work around works, but make sure you use the app's shortname, and not the name:

``` json
{"deploy":{"app_short_name":{"database":{"adapter":"postgresql","type":"postgresql"}}}}  
```

**Comment by basicsandwich** [comment] 2015-03-27 00:02
It's incredible that this still isn't fixed, almost a year later.  I've confirmed that this is STILL a problem.

**Comment by nickstamas** [comment] 2015-03-27 02:38
@johntxi +1

**Comment by cacheflow** [comment] 2015-03-31 23:16
I just ran into this problem. Like sudhirj said my rake db:migrate keeps failing as well and soon as I turned it off, OpsWorks gave me all green checks. How is this not fixed yet? And is there any other way to migrate my database once it's deployed?

**Comment by mshappe** [comment] 2015-04-01 16:07
I have come to the conclusion that, for whatever reason, the OpsWorks team just doesn't care about PostgreSQL support. It's sad, and it pretty much guarantees I can't use that service to simplify things, but such is life.

**Comment by saurabhbhatia** [comment] 2015-04-07 07:43
Its surprising the PR #166  has not been merged yet. @awsrequena you guys can change the case switch statements later, at least fix this issue fix for the existing users.

**Comment by segantii-alex-falkowski** [comment] 2015-05-06 02:25
Still nothing?

**Comment by segantii-alex-falkowski** [comment] 2015-05-06 02:28
I really don't understand why you have to mess with the database.yml in the first place.

**Comment by eggie5** [comment] 2015-06-13 01:00
What's the status on this??

**Comment by johncblandii** [comment] 2015-06-13 04:41
Custom json works just fine. Nothing is broken. See baruchlubinsky's answer advice. Just change the short name to your app sorry name.

**Comment by amalagaura** [comment] 2015-08-02 01:52
2015 and we are still looking Googling on how to use Postgres with Opsworks.

**Comment by johncblandii** [comment] 2015-08-02 03:16
Nope. It works without a problem. See @zacstewart's post above. It's exactly how I do it in 5 different stacks.

**Comment by amalagaura** [comment] 2015-08-03 01:49
@johncblandii Yes it works after you search google and come to this issue. 

Anyway there are a bunch of issues including no out of the box support for asset precompiles. It is ok if one spends a few hours searching and solving the problem on your own of course.

**Comment by johncblandii** [comment] 2015-08-03 01:59
The docs tell you the same thing as this issue.

Create `deploy/before_symlink.rb` and put this in there: `run "cd #{release_path} && RAILS_ENV=production bundle exec rake assets:precompile"`.

AWS is just normal Chef stuff. It has a larger learning curve if you haven't used it before (say with Engine Yard or similar) but the AWS docs and forums have these details in them.

With that said, I 100% agree some things should be built in. If the RDS database is Postgres, use the PG adapter. Those sort of things just make sense to get built into their system.

**Comment by johncblandii** [comment] 2015-08-03 02:03
Here're the custom db parts in the [AWS docs](http://docs.aws.amazon.com/opsworks/latest/userguide/workingapps-connectdb.html).

Here're the deployment hooks in the [AWS docs](http://docs.aws.amazon.com/opsworks/latest/userguide/workingcookbook-extend-hooks.html).

**Comment by stevenspiel** [comment] 2016-04-01 19:21
One thing I would change to @zacstewart's answer is to fix a minor typo from `postrgesql` to `postgresql`

```
{"deploy":{"app_short_name":{"database":{"adapter":"postgresql","type":"postgresql"}}}}
```

**Comment by jweiss** [comment] 2018-11-05 12:55
closing as this is a very old issue

**Closed as completed by jweiss** 2018-11-05 12:55 UTC
Labels: duplicate
